#!/bin/bash
cd $OPENSHIFT_REPO_DIR
sed -i 's/@OPENSHIFT_DIY_IP@/'"$OPENSHIFT_DIY_IP"'/g' inventory-openshift.yml
sed -i 's/@OPENSHIFT_DIY_PORT@/'"$OPENSHIFT_DIY_PORT"'/g' inventory-openshift.yml

sed -i 's/@OPENSHIFT_POSTGRESQL_DB_USERNAME@/'"$OPENSHIFT_POSTGRESQL_DB_USERNAME"'/g' inventory-openshift.yml
sed -i 's/@OPENSHIFT_POSTGRESQL_DB_PASSWORD@/'"$OPENSHIFT_POSTGRESQL_DB_PASSWORD"'/g' inventory-openshift.yml

sed -i 's/@OPENSHIFT_POSTGRESQL_DB_HOST@/'"$OPENSHIFT_POSTGRESQL_DB_HOST"'/g' inventory-openshift.yml
sed -i 's/@OPENSHIFT_POSTGRESQL_DB_NAME@/'"$OPENSHIFT_POSTGRESQL_DB_NAME"'/g' inventory-openshift.yml
