language: java
jdk:
- oraclejdk8
after_success:
- mvn cobertura:cobertura coveralls:report
deploy:
  provider: openshift
  user: bi-@freemail.hu
  password:
    secure: 0TCpq4dvQi1Fdva7+C7b9PFLxsblBzojWP0revwbI3FzVXgSE7pZhrVTXK4Ae0dHTsc0ErHQ1annOhSvFwuXzsJVJ+aqsvSZqARk+kezAGl32X0I0ny+08yatved8AjJe5f0MeqwxiK8PUt+r6+10wkoXawS8rNWCr0Te2DjME1IkRGTOYQMv3TQdXccUNtEyG6HyVXm/9Lqz0KMndvqvK1zIrXYtiD3hpM/BMMofcq+Db3IiXCFlbWD8C1VMJME7qDrQqOPgjiIbao7dCZnVitq+P74jyMRTFHd3iQfxPzeCoi4LjQC4zokIXr+PYOibaKqqeLx95bR6z/yAiFm6TuCh+/yvGg1QX9rJnU6vhU7LPWizj5J4luOtZIfDpG5AvNsf7OIfIha/+lEBlFVJ+uoGoiRH+7Z1sR6FmnYlLXKmzgBv3SX451FjvHBmGqDhLDTnwxsf5pjK3GI1uPc0YB0jqg/iMIoQ90NNQPfK6odY9gFrcwtb4knNRDKF4HY3JdCSwZ+buiKOhVPEsv4axwFuXWz8Py4MzXvnPr2bKsibebtM88o+XXNDb+MEVkROlz8uKBozNQHqiSeQeztli7AvX9wOwYn11hj5HMNsauqxmvfo3xDEvoYbKoP9xJ+YdKGcvcQify9GOiEnMa7+l2BWt//xHZ6mWNNa5BSW9M=
  app: dwi
  domain: balassai
  on:
    repo: bi-/dwi
